add container prune to remove existing container

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -53,28 +53,30 @@ jobs:
           tags: chatinun/learningdevops:latest
           context: .
   deploy:
+    needs: build  # Ensures deploy waits for build to finish
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout Code
-      uses: actions/checkout@v3
+      - name: Checkout Code
+        uses: actions/checkout@v3
 
-    - name: SSH into EC2 and Run Commands
-      run: |
-        # Save the private key from the secret to a temporary file
-        echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
-        chmod 600 ec2_key.pem
-        
-        # Use the saved private key to SSH into the instance
-        ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
-          # Commands to execute on the EC2 instance
-            # Log in to Docker Hub using the passed credentials
-            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin
-            docker pull your-dockerhub-username/your-image:latest
-            docker stop your-container-name || true
-            docker rm your-container-name || true
-            docker run -d --name java-container  -p 80:80 chatinun/learningdevops:latest
-        EOF
-        
-        # Clean up the temporary key file
-        rm -f ec2_key.pem
+      - name: SSH into EC2 and Run Commands
+        run: |
+          # Save the private key from the secret to a temporary file
+          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
+          chmod 600 ec2_key.pem
+          
+          # Use the saved private key to SSH into the instance
+          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
+            # Commands to execute on the EC2 instance
+              # Log in to Docker Hub using the passed credentials
+              echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin
+              docker pull your-dockerhub-username/your-image:latest
+              docker stop your-container-name || true
+              docker container prune -f
+              docker rm your-container-name || true
+              docker run -d --name java-container  -p 80:80 chatinun/learningdevops:latest
+          EOF
+          
+          # Clean up the temporary key file
+          rm -f ec2_key.pem
